[env:yd_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

; Standard 125MHz for absolute USB stability
board_build.f_cpu = 125000000L

; Use built-in TinyUSB stack from the core
build_flags = 
    -DUSE_TINYUSB
    -O3

lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.12.3
