[env:yd_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

; 133MHz is optimal for RP2040 stability and heat
board_build.f_cpu = 133000000L

build_flags = 
    -DUSE_TINYUSB
    -O3
    -ffast-math

; Force 1000Hz USB polling
board_build.usb_hid.poll_interval = 1 

lib_deps = 
    adafruit/Adafruit TinyUSB Library @ ^3.3.3
    adafruit/Adafruit NeoPixel @ ^1.12.3
